//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenomeNotepad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\Projects\\Genome Studio\\Test Data")]
        public string StartDirectory {
            get {
                return ((string)(this["StartDirectory"]));
            }
            set {
                this["StartDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SequenceUnit {
            get {
                return ((int)(this["SequenceUnit"]));
            }
            set {
                this["SequenceUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SequenceAddressModeBase {
            get {
                return ((int)(this["SequenceAddressModeBase"]));
            }
            set {
                this["SequenceAddressModeBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SequenceAddressModeCodon {
            get {
                return ((int)(this["SequenceAddressModeCodon"]));
            }
            set {
                this["SequenceAddressModeCodon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SequenceAddressGroupDigits {
            get {
                return ((bool)(this["SequenceAddressGroupDigits"]));
            }
            set {
                this["SequenceAddressGroupDigits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SequenceColumnCountBase {
            get {
                return ((int)(this["SequenceColumnCountBase"]));
            }
            set {
                this["SequenceColumnCountBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int SequenceColumnCountCodon {
            get {
                return ((int)(this["SequenceColumnCountCodon"]));
            }
            set {
                this["SequenceColumnCountCodon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SequenceGroupWidthBase {
            get {
                return ((int)(this["SequenceGroupWidthBase"]));
            }
            set {
                this["SequenceGroupWidthBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SequenceGroupWidthCodon {
            get {
                return ((int)(this["SequenceGroupWidthCodon"]));
            }
            set {
                this["SequenceGroupWidthCodon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SequenceCodonWidth {
            get {
                return ((int)(this["SequenceCodonWidth"]));
            }
            set {
                this["SequenceCodonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SequenceColumnDividerWidth {
            get {
                return ((int)(this["SequenceColumnDividerWidth"]));
            }
            set {
                this["SequenceColumnDividerWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long SequenceOrigin {
            get {
                return ((long)(this["SequenceOrigin"]));
            }
            set {
                this["SequenceOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public long SequenceBlockSize {
            get {
                return ((long)(this["SequenceBlockSize"]));
            }
            set {
                this["SequenceBlockSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000,000,000,000")]
        public string AddressFormatBase {
            get {
                return ((string)(this["AddressFormatBase"]));
            }
            set {
                this["AddressFormatBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00,000")]
        public string AddressFormatCodon {
            get {
                return ((string)(this["AddressFormatCodon"]));
            }
            set {
                this["AddressFormatCodon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int SequenceGroupCountBase {
            get {
                return ((int)(this["SequenceGroupCountBase"]));
            }
            set {
                this["SequenceGroupCountBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SequenceGroupCountCodon {
            get {
                return ((int)(this["SequenceGroupCountCodon"]));
            }
            set {
                this["SequenceGroupCountCodon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SequenceEncoding {
            get {
                return ((int)(this["SequenceEncoding"]));
            }
            set {
                this["SequenceEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SequenceUpperCase {
            get {
                return ((bool)(this["SequenceUpperCase"]));
            }
            set {
                this["SequenceUpperCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SequenceStrand {
            get {
                return ((int)(this["SequenceStrand"]));
            }
            set {
                this["SequenceStrand"] = value;
            }
        }
    }
}
